runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /ray/position/record/.*
  script: position.app
  login: admin

- url: /ray/position/search/.*
  script: position.app

- url: /ray/shorthand/.*
  script: shorthand.app

- url: /ray/serialization/.*
  script: serialization.app

- url: /ray/.*
  script: ray.app

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /position.js
  static_files: resources/position.js
  upload: resources/position.js
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
