runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /ray/shorthand/.*
  script: shorthand.app

- url: /ray/.*
  script: ray.app

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
